spring:
    application:
        name: itmokka
    datasource:
        url: jdbc:postgresql://localhost:5432/itmokka
        username: admin
        password: password
        driver-class-name: org.postgresql.Driver
    liquibase:
        enabled: true
        change-log: classpath:db/changelog.xml